apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helmbase.fullname" . }}
  labels:
    {{- include "helmbase.labels" . | nindent 4 }}
    {{- if $.Values.commonLabels }}
    {{- include "tpl.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- with .Values.commonAnnotations }}
  annotations: {{- include "tpl.render" ( dict "value" . "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "helmbase.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- if .Values.customConfigMaps }}
        checksum/configMaps: {{ include "tpl.render" (dict "value" .Values.customConfigMaps "context" $) | sha256sum }}
        {{- end }}
        {{- if .Values.customSecrets }}
        checksum/secrets: {{ include "tpl.render" (dict "value" .Values.customSecrets "context" $) | sha256sum }}
        {{- end }}
        {{- if .Values.podAnnotations }}
        {{- include "tpl.render" (dict "value" .Values.podAnnotations "context" $) | nindent 8 }}
        {{- end }}
        {{- if .Values.chartCheckSum }}
        chartCheckSum: {{ .Values.chartCheckSum | toString }}
        {{- end }}
      labels:
        {{- include "helmbase.selectorLabels" . | nindent 8 }}
        {{- if .Values.podLabels }}
        {{- include "tpl.render" (dict "value" .Values.podLabels "context" $) | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "helmbase.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.customInitContainers }}
      initContainers:
      {{- range .Values.customInitContainers }}
      - {{- include "tpl.render" (dict "value" . "context" $) | nindent 8 }}
      {{- end }}
      {{- end }}
      containers:
        - name: {{ include "helmbase.fullname" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}/{{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          {{- if .Values.customCommand }}
          command: {{- include "tpl.render" (dict "value" .Values.customCommand "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.customArgs }}
          args: {{- include "tpl.render" (dict "value" .Values.customArgs "context" $) | nindent 12 }}
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.ports }}
          ports: {{- include "tpl.render" (dict "value" .Values.ports "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.customLivenessProbe }}
          livenessProbe: {{- include "tpl.render" (dict "value" .Values.customLivenessProbe "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.customReadinessProbe }}
          readinessProbe: {{- include "tpl.render" (dict "value" .Values.customReadinessProbe "context" $) | nindent 12 }}
          {{- end }}          
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.extraEnvVars }}
          env:
            {{- include "tpl.render" (dict "value" .Values.extraEnvVars "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.customVolumeMounts }}
          volumeMounts: {{- include "tpl.render" (dict "value" .Values.customVolumeMounts "context" $) | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.customVolumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}  
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.customDnsConfig }}
      dnsConfig:
        {{- toYaml . | nindent 8 }}
      {{- end }}
