{{- if .Values.customSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helmbase.fullname" . }}
  labels:
    {{- include "helmbase.labels" . | nindent 4 }}
    {{- if $.Values.commonLabels }}
    {{- include "tpl.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- with .Values.commonAnnotations }}
  annotations: {{- include "tpl.render" ( dict "value" . "context" $ ) | nindent 4 }}
  {{- end }}
data:
{{- range $key, $data := .Values.customSecrets }}
  {{ $key }}: {{ $data | quote }}
{{- end -}}
{{- end -}}
