{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helmbase.serviceAccountName" . }}
  labels:
    {{- include "helmbase.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "tpl.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.commonAnnotations  .Values.serviceAccount.annotations }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- include "tpl.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
  {{- end }}

{{- end }}
